version: '3.4'
 
networks:
  mydockerapi-dev:
    driver: bridge 
 
services:
  mydockerapi:
    image: crudcustomers:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=customersdb;username=postgres;password=postgres"
    networks:
      - crudcustomers-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "customersdb"
    networks:
      - crudcustomers-dev
volumes:
  db_volume:
         